# Generated by Django 3.0.3 on 2020-02-23 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200223_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePartyRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo_room_image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='photos',
            name='partyroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.CreatePartyRoom'),
            preserve_default=False,
        ),
    ]
