# Generated by Django 3.0.3 on 2020-02-23 17:02

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200223_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpartyroom',
            name='room_code',
            field=models.CharField(default=home.models.id_generator, max_length=60),
        ),
    ]
