# Generated by Django 3.0.3 on 2020-02-24 21:15

import django.core.validators
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_createpartyroom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo_room_image',
            field=models.ImageField(default=1, upload_to=home.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
            preserve_default=False,
        ),
    ]
