# Generated by Django 3.0.3 on 2020-02-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200224_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpartyroom',
            name='total_pictures',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
